import { defineTextStyles } from "@pandacss/dev";

export const textStyles = defineTextStyles({
  "title-60-700": {
    description: "Large title text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "60px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "72px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-40-400": {
    description: "Medium title text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "40px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "52px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-40-700": {
    description: "Medium title text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "40px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "52px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-32-400": {
    description: "Small title text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "32px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "42px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-32-700": {
    description: "Small title text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "32px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "42px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-24-400": {
    description: "Subtitle text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "24px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "34px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-24-700": {
    description: "Subtitle text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "24px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "34px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-18-400": {
    description: "Small subtitle text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "18px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "26px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "title-18-700": {
    description: "Small subtitle text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "18px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "26px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-16-400": {
    description: "Default body text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "16px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "24px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-16-500": {
    description: "Default body text with medium weight",
    value: {
      fontFamily: "Inter",
      fontSize: "16px",
      fontWeight: "500",
      letterSpacing: "-0.4px",
      lineHeight: "24px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-16-700": {
    description: "Default body text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "16px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "24px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-14-400": {
    description: "Small body text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "14px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "20px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-14-500": {
    description: "Small body text with medium weight",
    value: {
      fontFamily: "Inter",
      fontSize: "14px",
      fontWeight: "500",
      letterSpacing: "-0.4px",
      lineHeight: "20px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-14-700": {
    description: "Small body text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "14px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "20px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-12-400": {
    description: "Extra small body text with regular weight",
    value: {
      fontFamily: "Inter",
      fontSize: "12px",
      fontWeight: "400",
      letterSpacing: "-0.4px",
      lineHeight: "16px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-12-500": {
    description: "Extra small body text with medium weight",
    value: {
      fontFamily: "Inter",
      fontSize: "12px",
      fontWeight: "500",
      letterSpacing: "-0.4px",
      lineHeight: "16px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  "body-12-700": {
    description: "Extra small body text with bold weight",
    value: {
      fontFamily: "Inter",
      fontSize: "12px",
      fontWeight: "700",
      letterSpacing: "-0.4px",
      lineHeight: "16px",
      textDecoration: "None",
      textTransform: "None",
    },
  },
});
